### ISSUE TITLE
Anniversary Update

### ISSUE THREAD

**Issue by IlliterateJam** [orare/DurableBears#1]
Hello Orare, I had been playing your mod for a while but unfortunately the anniversary update has broken adding the armor. The fix is quick as all you have to do in AddBearArmor()  is change var itemCount = self.inventory.GetItemCount(ItemIndex.Bear); to var itemCount = self.inventory.GetItemCount(RoR2Content.Items.Bear);. I found this out by myself and incorporated it in a personal mod that only I have been using. I just wanted to let you know this should you still be active and want to update it, as I really appreciate this mod. If you are inactive and I dont hear back from you for a while I will republish the mod and give you full credit to the code. Thank you. 

Ben

**Comment by orare** [comment]
Thank you for letting me know and providing a fix alongside it. I went ahead and made the changes and they should be live now on thunderstore
